version: "3"

services:
  mongodb:
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - '27018:27017'
    volumes:
      - db:/data/db
  backend:
    depends_on:
      - mongodb
    build: ./api
    restart: always
    env_file: ./.env
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
  frontend:
      build: ./client
      ports:
        - "8080:8080"

volumes:
  db:
